/*
Copyright (c) 2018-2023 Festo SE & Co. KG <https://www.festo.com/net/de_de/Forms/web/contact_international>
Author: Michael Hoffmeister

This source code is licensed under the Apache License 2.0 (see LICENSE.txt).

This source code may use other Open Source software components (see LICENSE.txt).
*/

using System.Linq;
using Aas = AasCore.Aas3_1;

// reSharper disable UnusedType.Global
// reSharper disable ClassNeverInstantiated.Global

namespace AasxPredefinedConcepts
{
    /// <summary>
    /// This class holds definitions, which are preliminary, experimental, partial, not stabilized.
    /// The definitions aim as the definition and handling of Events.
    /// The should end up finally in a AASiD specification.
    /// </summary>
    public class SmtAdditions : AasxDefinitionBase
    {
        public static SmtAdditions Static = new SmtAdditions();

        public Aas.ConceptDescription
            CD_ContactInfoPreviewFile,
            CD_SmtTemplateTemplate,
            CD_SmtCopyElements;

        public Aas.IKey
            Key_SmtDropinDefinition,
            Key_SmtDropinUse;

        public Aas.IQualifier
            Qual_SmtAutoGenerated;

        public SmtAdditions()
        {
            // info
            this.DomainInfo = "AAS Submodel templates - Additional (non standard) information";

            // definitons
            CD_ContactInfoPreviewFile = CreateSparseConceptDescription("en", "IRI",
                "ContactInfoPreviewFile",
                "https://admin-shell.io/tmp/SMT/Additions/ContactInformation/PreviewFile",
                @"Provides a preview image of the contact, e.g. an image of a person or a symbolic pictuture, in a commonly used image format and low resolution.");

            // SMT dropins
            Key_SmtDropinDefinition = new Aas.Key(Aas.KeyTypes.GlobalReference,
                "https://admin-shell.io/smt-dropin/smt-dropin-definition/1/0");

            Key_SmtDropinUse = new Aas.Key(Aas.KeyTypes.GlobalReference,
                "https://admin-shell.io/smt-dropin/smt-dropin-use/1/0");

            // Template templates
            CD_SmtTemplateTemplate = CreateSparseConceptDescription("en", "IRI",
                "SMT/TemplateTemplate",
                "https://admin-shell.io/tmp/SMT/Additions/SmtTemplateTemplate/Submodel/1/0",
                @"Submodel template containing information about another Submodel template is to be built.");

            CD_SmtCopyElements = CreateSparseConceptDescription("en", "IRI",
                "SMT/CopyElements",
                "https://admin-shell.io/tmp/SMT/Additions/SmtTemplateTemplate/CopyElements/1/0",
                @"Copy named elements to another Submodel element.");

            Qual_SmtAutoGenerated = CreateSparseQualifier(Aas.QualifierKind.TemplateQualifier,
                "SMT/AutoGenerated", Aas.DataTypeDefXsd.String,
                "https://admin-shell.io/SubmodelTemplates/NoDefinition/1/0");

            // reflect
            AddEntriesByReflection(this.GetType(), useAttributes: false, useFieldNames: true);
        }
    }
}
