/*
Copyright (c) 2018-2023 Festo SE & Co. KG
<https://www.festo.com/net/de_de/Forms/web/contact_international>
Author: Michael Hoffmeister

This source code is licensed under the Apache License 2.0 (see LICENSE.txt).

This source code may use other Open Source software components (see LICENSE.txt).

This source code was auto-generated by the AASX Package Explorer.
*/

using AasCore.Aas3_0;
using AasxIntegrationBase;
using AdminShellNS;
using Extensions;
using System;
using System.Collections.Generic;
using Aas = AasCore.Aas3_0;

namespace AasxPredefinedConcepts.ProductChangeNotifications.Base
{

    public interface ICD_RecordsOfPcn
    {
        public List<ICD_Record> Record { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_Record
    {
        public ICD_Manufacturer Manufacturer { get; set; }
        public string ManufacturerChangeID { get; set; }
        public string PcnType { get; set; }
        public ICD_LifeCycleData LifeCycleData { get; set; }
        public ICD_ReasonsOfChange ReasonsOfChange { get; set; }
        public ICD_ItemCategories ItemCategories { get; set; }
        public ICD_AffectedPartNumbers AffectedPartNumbers { get; set; }
        public List<ILangStringTextType> PcnReasonComment { get; set; }
        public ICD_PcnChangeInformation PcnChangeInformation { get; set; }
        public ICD_AdditionalInformations AdditionalInformation { get; set; }
        public string DateOfRecord { get; set; }
        public ICD_ItemOfChange ItemOfChange { get; set; }
        public ICD_RecommendedItems RecommendedItems { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_Manufacturer
    {
        public List<ILangStringTextType> ManufacturerName { get; set; }
        public ICD_Address AdressInformation { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_Address
    {

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_LifeCycleData
    {
        public List<ICD_LifeCycleMilestone> Milestone { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_LifeCycleMilestone
    {
        public string MilestoneClassification { get; set; }
        public string DateOfValidity { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ReasonsOfChange
    {
        public List<ICD_ReasonOfChange> ReasonOfChange { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ReasonOfChange
    {
        public string ReasonClassificationSystem { get; set; }
        public string VersionOfClassificationSystem { get; set; }
        public string ReasonId { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ItemCategories
    {
        public List<ICD_ItemCategory> ItemCategory { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ItemCategory
    {
        public string ItemClassificationSystem { get; set; }
        public string VersionOfClassificationSystem { get; set; }
        public string ItemCategory { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_AffectedPartNumbers
    {
        public List<string> AffectedPartNumber { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_PcnChangeInformation
    {
        public List<ILangStringTextType> ChangeTitle { get; set; }
        public List<ILangStringTextType> ChangeDetail { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_AdditionalInformations
    {
        public List<AasClassMapperFile> AdditionalInformation { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ItemOfChange
    {
        public List<ILangStringTextType> ManufacturerProductFamily { get; set; }
        public List<ILangStringTextType> ManufacturerProductDesignation { get; set; }
        public List<ILangStringTextType> OrderCodeOfManufacturer { get; set; }
        public AasClassMapperHintedReference ManufacturerAssetID { get; set; }
        public ICD_ProductClassifications ProductClassifications { get; set; }
        public string HardwareVersion { get; set; }
        public UInt64? RemainingAmountAvailable { get; set; }
        public ICD_TechnicalData_Changes TechnicalData_Changes { get; set; }
        public ICD_TechnicalData_CurrentState TechnicalData_CurrentState { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ProductClassifications
    {
        public List<ICD_ProductClassification> ProductClassification { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ProductClassification
    {
        public string ClassificationSystem { get; set; }
        public string VersionOfClassificationSystem { get; set; }
        public string ProductClassId { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_Changes
    {
        public List<ICD_SingleChange> SingleChange { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_SingleChange
    {
        public string Arbitrary { get; set; }
        public AasClassMapperHintedReference OriginOfChange { get; set; }
        public string ReasonId { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_CurrentState
    {
        public List<string> Arbitrary { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_RecommendedItems
    {
        public List<ICD_RecommendedItem> RecommendedItem { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_RecommendedItem
    {
        public List<ILangStringTextType> ManufacturerProductFamily { get; set; }
        public List<ILangStringTextType> ManufacturerProductDesignation { get; set; }
        public List<ILangStringTextType> OrderCodeOfManufacturer { get; set; }
        public ICD_ProductClassifications ProductClassifications { get; set; }
        public ICD_TechnicalData_Fit TechnicalData_Fit { get; set; }
        public ICD_TechnicalData_Form TechnicalData_Form { get; set; }
        public ICD_TechnicalData_Function TechnicalData_Function { get; set; }
        public ICD_TechnicalData_Other TechnicalData_Other { get; set; }
        public string IncotermCode { get; set; }
        public Int32? DeliveryTimeClassOtherRegion { get; set; }
        public Int32? DeliveryTimeClassSameRegion { get; set; }
        public ICD_ConformityDeclarations ConformityDeclarations { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_Fit
    {
        public float? TargetEstimate { get; set; }
        public string Arbitrary { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_Form
    {
        public float? TargetEstimate { get; set; }
        public string Arbitrary { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_Function
    {
        public float? TargetEstimate { get; set; }
        public string Arbitrary { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_TechnicalData_Other
    {
        public float? TargetEstimate { get; set; }
        public string Arbitrary { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ConformityDeclarations
    {

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }

    public interface ICD_ProductChangeNotifications
    {
        public ICD_RecordsOfPcn Records { get; set; }

        // auto-generated informations
        public AasClassMapperInfo __Info__ { get; set; }
    }
}