/*
Copyright (c) 2018-2023 Festo SE & Co. KG
<https://www.festo.com/net/de_de/Forms/web/contact_international>
Author: Michael Hoffmeister

This source code is licensed under the Apache License 2.0 (see LICENSE.txt).

This source code may use other Open Source software components (see LICENSE.txt).

This source code was auto-generated by the AASX Package Explorer.
*/

using AasCore.Aas3_1;
using System;
using System.Collections.Generic;
using System.Linq;
using PCNPRE = AasxPredefinedConcepts.ProductChangeNotifications.V_1_0_pre;

namespace AasxPredefinedConcepts.ProductChangeNotifications.V_1_0
{
    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/Record/List/1/0")]
    public class CD_RecordsOfPcn
    {
        [AasConcept(Cd = "0173-1#02-ABI294#003/0173-1#01-AHE583#003", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<CD_Record> Record = (new List<CD_Record>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_RecordsOfPcn()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_RecordsOfPcn(PCNPRE.CD_RecordsOfPcn other)
        {
            if (other.Record != null)
                Record = new List<CD_Record>(other.Record.Select((o) => new CD_Record(o)));
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI294#003/0173-1#01-AHE583#003")]
    public class CD_Record
    {
        [AasConcept(Cd = "0173-10029#01-XFB003#001/0173-1#01-AHE584#003", Card = AasxPredefinedCardinality.One)]
        public CD_Manufacturer Manufacturer = new CD_Manufacturer();

        [AasConcept(Cd = "0173-1#02-ABG772#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string ManufacturerChangeID;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/PcnType/1/0", Card = AasxPredefinedCardinality.One)]
        public string PcnType;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/LifeCycleData/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_LifeCycleData LifeCycleData = null;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ReasonOfChange/List/1/0", Card = AasxPredefinedCardinality.One)]
        public CD_ReasonsOfChange ReasonsOfChange = new CD_ReasonsOfChange();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/List/1/0", Card = AasxPredefinedCardinality.One)]
        public CD_ItemCategories ItemCategories = new CD_ItemCategories();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AffectedPartNumber/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_AffectedPartNumbers AffectedPartNumbers = null;

        [AasConcept(Cd = "0173-1#02-ABF814#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public List<ILangStringTextType> PcnReasonComment = null;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/PcnChangeInformation/1/0", Card = AasxPredefinedCardinality.One)]
        public CD_PcnChangeInformation PcnChangeInformation = new CD_PcnChangeInformation();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AdditionalInformation/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_AdditionalInformations AdditionalInformation = null;

        [AasConcept(Cd = "0173-1#02-ABF816#003", Card = AasxPredefinedCardinality.One)]
        public string DateOfRecord;

        [AasConcept(Cd = "0173-1#02-ABI297#003/0173-1#01-AHE586#003", Card = AasxPredefinedCardinality.One)]
        public CD_ItemOfChange ItemOfChange = new CD_ItemOfChange();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/RecommendedItem/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_RecommendedItems RecommendedItems = null;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_Record()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_Record(PCNPRE.CD_Record other)
        {
            Manufacturer = new CD_Manufacturer(other.Manufacturer);
            ManufacturerChangeID = other.ManufacturerChangeID;
            PcnType = other.PcnType;
            LifeCycleData = (other.LifeCycleData == null) ? null : new CD_LifeCycleData(other.LifeCycleData);
            ReasonsOfChange = new CD_ReasonsOfChange(other.ReasonsOfChange);
            ItemCategories = new CD_ItemCategories(other.ItemCategories);
            AffectedPartNumbers = (other.AffectedPartNumbers == null) ? null : new CD_AffectedPartNumbers(other.AffectedPartNumbers);
            PcnReasonComment = (other.PcnReasonComment == null) ? null : new List<ILangStringTextType>(other.PcnReasonComment);
            PcnChangeInformation = new CD_PcnChangeInformation(other.PcnChangeInformation);
            AdditionalInformation = (other.AdditionalInformations == null) ? null : new CD_AdditionalInformations(other.AdditionalInformations);
            DateOfRecord = other.DateOfRecord;
            ItemOfChange = new CD_ItemOfChange(other.ItemOfChange);
            RecommendedItems = (other.RecommendedItems == null) ? null : new CD_RecommendedItems(other.RecommendedItems);
        }
    }

    [AasConcept(Cd = "0173-10029#01-XFB003#001/0173-1#01-AHE584#003")]
    public class CD_Manufacturer
    {
        [AasConcept(Cd = "0173-1#02-AAO677#004", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ManufacturerName = new List<ILangStringTextType>();

        [AasConcept(Cd = "0173-1#02-ABG791#003", Card = AasxPredefinedCardinality.One)]
        public CD_Address AdressInformation = new CD_Address();

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_Manufacturer()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_Manufacturer(PCNPRE.CD_Manufacturer other)
        {
            ManufacturerName = new List<ILangStringTextType>(other.ManufacturerName);
            AdressInformation = new CD_Address(other.AdressInformation);
        }
    }

    [AasConcept(Cd = "0173-1#02-ABG791#003")]
    public class CD_Address
    {

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_Address()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_Address(PCNPRE.CD_Address other)
        {
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/LifeCycleData/List/1/0")]
    public class CD_LifeCycleData
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/LifeCycleData/Milestone/1/0", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<CD_LifeCycleMilestone> Milestone = (new List<CD_LifeCycleMilestone>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_LifeCycleData()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_LifeCycleData(PCNPRE.CD_LifeCycleData other)
        {
            if (other.Milestone != null)
                Milestone = new List<CD_LifeCycleMilestone>(other.Milestone.Select((o) => new CD_LifeCycleMilestone(o)));
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/LifeCycleData/Milestone/1/0")]
    public class CD_LifeCycleMilestone
    {
        [AasConcept(Cd = "0173-1#02-ABG773#002", Card = AasxPredefinedCardinality.One)]
        public string MilestoneClassification;

        [AasConcept(Cd = "0173-1#02-ABF815#002", Card = AasxPredefinedCardinality.One)]
        public string DateOfValidity;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_LifeCycleMilestone()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_LifeCycleMilestone(PCNPRE.CD_LifeCycleMilestone other)
        {
            MilestoneClassification = other.MilestoneClassification;
            DateOfValidity = other.DateOfValidity;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ReasonOfChange/List/1/0")]
    public class CD_ReasonsOfChange
    {
        [AasConcept(Cd = "0173-1#02-ABI296#002/0173-1#01-AHE585#002", Card = AasxPredefinedCardinality.OneToMany)]
        public List<CD_ReasonOfChange> ReasonOfChange = (new List<CD_ReasonOfChange>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ReasonsOfChange()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ReasonsOfChange(PCNPRE.CD_ReasonsOfChange other)
        {
            if (other.ReasonOfChange != null)
                ReasonOfChange = new List<CD_ReasonOfChange>(other.ReasonOfChange.Select((o) => new CD_ReasonOfChange(o)));
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI296#002/0173-1#01-AHE585#002")]
    public class CD_ReasonOfChange
    {
        [AasConcept(Cd = "0173-1#02-ABF813#002", Card = AasxPredefinedCardinality.One)]
        public string ReasonClassificationSystem;

        [AasConcept(Cd = "0173-1#02-AAR710#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string VersionOfClassificationSystem;

        [AasConcept(Cd = "0173-1#02-ABG774#002", Card = AasxPredefinedCardinality.One)]
        public string ReasonId;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ReasonOfChange()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ReasonOfChange(PCNPRE.CD_ReasonOfChange other)
        {
            ReasonClassificationSystem = other.ReasonClassificationSystem;
            VersionOfClassificationSystem = other.VersionOfClassificationSystem;
            ReasonId = other.ReasonId;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/List/1/0")]
    public class CD_ItemCategories
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/1/0", Card = AasxPredefinedCardinality.OneToMany)]
        public List<CD_ItemCategory> ItemCategory = (new List<CD_ItemCategory>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ItemCategories()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ItemCategories(PCNPRE.CD_ItemCategories other)
        {
            if (other.ItemCategory != null)
                ItemCategory = new List<CD_ItemCategory>(other.ItemCategory.Select((o) => new CD_ItemCategory(o)));
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/1/0")]
    public class CD_ItemCategory
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/ItemClassificationSystem/1/0", Card = AasxPredefinedCardinality.One)]
        public string ItemClassificationSystem;

        [AasConcept(Cd = "0173-1#02-AAR710#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string VersionOfClassificationSystem;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ItemCategory/ItemCategory/1/0", Card = AasxPredefinedCardinality.One)]
        public string ItemCategory;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ItemCategory()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ItemCategory(PCNPRE.CD_ItemCategory other)
        {
            ItemClassificationSystem = other.ItemClassificationSystem;
            VersionOfClassificationSystem = other.VersionOfClassificationSystem;
            ItemCategory = other.ItemCategory;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AffectedPartNumber/List/1/0")]
    public class CD_AffectedPartNumbers
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AffectedPartNumber/1/0", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<string> AffectedPartNumber = (new List<string>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_AffectedPartNumbers()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_AffectedPartNumbers(PCNPRE.CD_AffectedPartNumbers other)
        {
            AffectedPartNumber = other.AffectedPartNumber;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/PcnChangeInformation/1/0")]
    public class CD_PcnChangeInformation
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/PcnChangeInformation/ChangeTitle/1/0", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ChangeTitle = new List<ILangStringTextType>();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/PcnChangeInformation/ChangeDetail/1/0", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ChangeDetail = new List<ILangStringTextType>();

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_PcnChangeInformation()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_PcnChangeInformation(PCNPRE.CD_PcnChangeInformation other)
        {
            ChangeTitle = new List<ILangStringTextType>(other.ChangeTitle);
            ChangeDetail = new List<ILangStringTextType>(other.ChangeDetail);
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AdditionalInformation/List/1/0")]
    public class CD_AdditionalInformations
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/AdditionalInformation/AdditionalInformation/1/0", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<AasClassMapperFile> AdditionalInformation = (new List<AasClassMapperFile>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_AdditionalInformations()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_AdditionalInformations(PCNPRE.CD_AdditionalInformations other)
        {
            if (other.AdditionalInformation != null)
                AdditionalInformation = new List<AasClassMapperFile>(other.AdditionalInformation.Select((o) => new AasClassMapperFile(o)));
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI297#003/0173-1#01-AHE586#003")]
    public class CD_ItemOfChange
    {
        [AasConcept(Cd = "0173-1#02-AAU731#003", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ManufacturerProductFamily = new List<ILangStringTextType>();

        [AasConcept(Cd = "0173-1#02-AAW338#002", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ManufacturerProductDesignation = new List<ILangStringTextType>();

        [AasConcept(Cd = "0173-1#02-AAO227#004", Card = AasxPredefinedCardinality.ZeroToOne)]
        public List<ILangStringTextType> OrderCodeOfManufacturer = null;

        [AasConcept(Cd = "0173-1#02-ABG775#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public AasClassMapperHintedReference ManufacturerAssetID = null;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ProductClassification/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_ProductClassifications ProductClassifications = null;

        [AasConcept(Cd = "0173-1#02-AAN270#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string HardwareVersion;

        [AasConcept(Cd = "0173-1#02-BAF551#004", Card = AasxPredefinedCardinality.ZeroToOne)]
        public UInt64? RemainingAmountAvailable;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_Changes/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_Changes TechnicalData_Changes = null;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_CurrentState/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_CurrentState TechnicalData_CurrentState = null;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ItemOfChange()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ItemOfChange(PCNPRE.CD_ItemOfChange other)
        {
            ManufacturerProductFamily = new List<ILangStringTextType>(other.ManufacturerProductFamily);
            ManufacturerProductDesignation = new List<ILangStringTextType>(other.ManufacturerProductDesignation);
            OrderCodeOfManufacturer = (other.OrderCodeOfManufacturer == null) ? null : new List<ILangStringTextType>(other.OrderCodeOfManufacturer);
            ManufacturerAssetID = (other.ManufacturerAssetID == null) ? null : new AasClassMapperHintedReference(other.ManufacturerAssetID);
            ProductClassifications = (other.ProductClassifications == null) ? null : new CD_ProductClassifications(other.ProductClassifications);
            HardwareVersion = other.HardwareVersion;
            RemainingAmountAvailable = other.RemainingAmountAvailable;
            TechnicalData_Changes = (other.TechnicalData_Changes == null) ? null : new CD_TechnicalData_Changes(other.TechnicalData_Changes);
            TechnicalData_CurrentState = (other.TechnicalData_CurrentState == null) ? null : new CD_TechnicalData_CurrentState(other.TechnicalData_CurrentState);
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ProductClassification/List/1/0")]
    public class CD_ProductClassifications
    {
        [AasConcept(Cd = "0173-1#02-ABI298#002/0173-1#01-AHE587#002", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<CD_ProductClassification> ProductClassification = (new List<CD_ProductClassification>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ProductClassifications()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ProductClassifications(PCNPRE.CD_ProductClassifications other)
        {
            if (other.ProductClassification != null)
                ProductClassification = new List<CD_ProductClassification>(other.ProductClassification.Select((o) => new CD_ProductClassification(o)));
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI298#002/0173-1#01-AHE587#002")]
    public class CD_ProductClassification
    {
        [AasConcept(Cd = "0173-1#02-AAR709#002", Card = AasxPredefinedCardinality.One)]
        public string ClassificationSystem;

        [AasConcept(Cd = "0173-1#02-AAR710#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string VersionOfClassificationSystem;

        [AasConcept(Cd = "0173-1#02-ABG776#002", Card = AasxPredefinedCardinality.One)]
        public string ProductClassId;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ProductClassification()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ProductClassification(PCNPRE.CD_ProductClassification other)
        {
            ClassificationSystem = other.ClassificationSystem;
            VersionOfClassificationSystem = other.VersionOfClassificationSystem;
            ProductClassId = other.ProductClassId;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_Changes/List/1/0")]
    public class CD_TechnicalData_Changes
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_Changes/Change/1/0", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<CD_SingleChange> SingleChange = (new List<CD_SingleChange>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_Changes()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_Changes(PCNPRE.CD_TechnicalData_Changes other)
        {
            if (other.SingleChange != null)
                SingleChange = new List<CD_SingleChange>(other.SingleChange.Select((o) => new CD_SingleChange(o)));
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_Changes/Change/1/0")]
    public class CD_SingleChange
    {
        public string Arbitrary;

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_Changes/OriginOfChange/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public AasClassMapperHintedReference OriginOfChange = null;

        [AasConcept(Cd = "0173-1#02-ABG774#002", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string ReasonId;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_SingleChange()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_SingleChange(PCNPRE.CD_SingleChange other)
        {
            OriginOfChange = (other.Origin_of_change == null) ? null : new AasClassMapperHintedReference(other.Origin_of_change);
            ReasonId = other.ReasonId;
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/TechnicalData_CurrentState/List/1/0")]
    public class CD_TechnicalData_CurrentState
    {
        public List<string> Arbitrary = (new List<string>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_CurrentState()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_CurrentState(PCNPRE.CD_TechnicalData_CurrentState other)
        {
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/RecommendedItem/List/1/0")]
    public class CD_RecommendedItems
    {
        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/RecommendedItem/1/0", Card = AasxPredefinedCardinality.ZeroToMany)]
        public List<CD_RecommendedItem> RecommendedItem = (new List<CD_RecommendedItem>());

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_RecommendedItems()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_RecommendedItems(PCNPRE.CD_RecommendedItems other)
        {
            if (other.RecommendedItem != null)
                RecommendedItem = new List<CD_RecommendedItem>(other.RecommendedItem.Select((o) => new CD_RecommendedItem(o)));
        }
    }

    [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/RecommendedItem/1/0")]
    public class CD_RecommendedItem
    {
        [AasConcept(Cd = "0173-1#02-AAU731#003", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ManufacturerProductFamily = new List<ILangStringTextType>();

        [AasConcept(Cd = "0173-1#02-AAW338#002", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> ManufacturerProductDesignation = new List<ILangStringTextType>();

        [AasConcept(Cd = "0173-1#02-AAO227#004", Card = AasxPredefinedCardinality.One)]
        public List<ILangStringTextType> OrderCodeOfManufacturer = new List<ILangStringTextType>();

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/ProductClassification/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_ProductClassifications ProductClassifications = null;

        [AasConcept(Cd = "0173-1#02-ABI299#003/0173-1#01-AHE588#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_Fit TechnicalData_Fit = null;

        [AasConcept(Cd = "0173-1#02-ABI300#003/0173-1#01-AHE589#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_Form TechnicalData_Form = null;

        [AasConcept(Cd = "0173-10029#01-XFB010#001", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_Function TechnicalData_Function = null;

        [AasConcept(Cd = "0173-1#02-ABI302#003/0173-1#01-AHE591#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_TechnicalData_Other TechnicalData_Other = null;

        [AasConcept(Cd = "0173-1#02-AAO280#004", Card = AasxPredefinedCardinality.ZeroToOne)]
        public string IncotermCode;

        [AasConcept(Cd = "0173-1#02-ABG779#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public Int32? DeliveryTimeClassOtherRegion;

        [AasConcept(Cd = "0173-1#02-ABG778#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public Int32? DeliveryTimeClassSameRegion;

        [AasConcept(Cd = "0173-1#02-ABI303#003/0173-1#01-AHE592#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_ConformityDeclarations ConformityDeclarations = null;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_RecommendedItem()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_RecommendedItem(PCNPRE.CD_RecommendedItem other)
        {
            ManufacturerProductFamily = new List<ILangStringTextType>(other.ManufacturerProductFamily);
            ManufacturerProductDesignation = new List<ILangStringTextType>(other.ManufacturerProductDesignation);
            OrderCodeOfManufacturer = new List<ILangStringTextType>(other.OrderCodeOfManufacturer);
            ProductClassifications = (other.ProductClassifications == null) ? null : new CD_ProductClassifications(other.ProductClassifications);
            TechnicalData_Fit = (other.TechnicalData_Fit == null) ? null : new CD_TechnicalData_Fit(other.TechnicalData_Fit);
            TechnicalData_Form = (other.TechnicalData_Form == null) ? null : new CD_TechnicalData_Form(other.TechnicalData_Form);
            TechnicalData_Function = (other.TechnicalData_Function == null) ? null : new CD_TechnicalData_Function(other.TechnicalData_Function);
            TechnicalData_Other = (other.TechnicalData_Other == null) ? null : new CD_TechnicalData_Other(other.TechnicalData_Other);
            IncotermCode = other.Incotermcode;
            DeliveryTimeClassOtherRegion = other.DeliveryTimeClassOtherRegion;
            DeliveryTimeClassSameRegion = other.DeliveryTimeClassSameRegion;
            ConformityDeclarations = (other.ConformityDeclarations == null) ? null : new CD_ConformityDeclarations(other.ConformityDeclarations);
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI299#003/0173-1#01-AHE588#003")]
    public class CD_TechnicalData_Fit
    {
        [AasConcept(Cd = "0173-1#02-ABG777#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public float? TargetEstimate;

        public string Arbitrary;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_Fit()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_Fit(PCNPRE.CD_TechnicalData_Fit other)
        {
            TargetEstimate = other.TargetEstimate;
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI300#003/0173-1#01-AHE589#003")]
    public class CD_TechnicalData_Form
    {
        [AasConcept(Cd = "0173-1#02-ABG777#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public float? TargetEstimate;

        public string Arbitrary;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_Form()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_Form(PCNPRE.CD_TechnicalData_Form other)
        {
            TargetEstimate = other.TargetEstimate;
        }
    }

    [AasConcept(Cd = "0173-10029#01-XFB010#001")]
    public class CD_TechnicalData_Function
    {
        [AasConcept(Cd = "0173-1#02-ABG777#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public float? TargetEstimate;

        public string Arbitrary;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_Function()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_Function(PCNPRE.CD_TechnicalData_Function other)
        {
            TargetEstimate = other.TargetEstimate;
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI302#003/0173-1#01-AHE591#003")]
    public class CD_TechnicalData_Other
    {
        [AasConcept(Cd = "0173-1#02-ABG777#003", Card = AasxPredefinedCardinality.ZeroToOne)]
        public float? TargetEstimate;

        public string Arbitrary;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_TechnicalData_Other()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_TechnicalData_Other(PCNPRE.CD_TechnicalData_Other other)
        {
            TargetEstimate = other.TargetEstimate;
        }
    }

    [AasConcept(Cd = "0173-1#02-ABI303#003/0173-1#01-AHE592#003")]
    public class CD_ConformityDeclarations
    {

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ConformityDeclarations()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ConformityDeclarations(PCNPRE.CD_ConformityDeclarations other)
        {
        }
    }

    [AasConcept(Cd = "0173-1#01-AHE582#003")]
    public class CD_ProductChangeNotifications
    {

        [AasConcept(Cd = "http://admin-shell.io/VDMA/Fluidics/ProductChangeNotification/Record/List/1/0", Card = AasxPredefinedCardinality.ZeroToOne)]
        public CD_RecordsOfPcn Records = null;

        // auto-generated informations
        public AasClassMapperInfo __Info__ = null;

        // default constructor
        public CD_ProductChangeNotifications()
        {
        }

        // upgrade constructor (from PCNPRE namespace)
        public CD_ProductChangeNotifications(PCNPRE.CD_ProductChangeNotifications other)
        {
            Records = (other.Records == null) ? null : new CD_RecordsOfPcn(other.Records);
        }
    }
}


