// This file was automatically generated by doctest-csharp.
// !!! DO NOT EDIT OR APPEND !!!

using NUnit.Framework;

namespace AdminShell_V20.Tests
{
    public class DocTest_AasxCompatibilityModels_V20_AdminShellUtil_cs
    {
        [Test]
        public void AtLine39AndColumn12()
        {
            Assert.AreEqual("someName", AdminShellUtil.FilterFriendlyName("someName"));
        }

        [Test]
        public void AtLine40AndColumn12()
        {
            Assert.AreEqual("some__name", AdminShellUtil.FilterFriendlyName("some!;name"));
        }

        [Test]
        public void AtLine50AndColumn12()
        {
            Assert.IsFalse(AdminShellUtil.HasWhitespace(""));
        }

        [Test]
        public void AtLine51AndColumn12()
        {
            Assert.IsTrue(AdminShellUtil.HasWhitespace(" "));
        }

        [Test]
        public void AtLine52AndColumn12()
        {
            Assert.IsTrue(AdminShellUtil.HasWhitespace("aa bb"));
        }

        [Test]
        public void AtLine53AndColumn12()
        {
            Assert.IsTrue(AdminShellUtil.HasWhitespace(" aabb"));
        }

        [Test]
        public void AtLine54AndColumn12()
        {
            Assert.IsTrue(AdminShellUtil.HasWhitespace("aabb "));
        }

        [Test]
        public void AtLine55AndColumn12()
        {
            Assert.IsFalse(AdminShellUtil.HasWhitespace("aabb"));
        }

        [Test]
        public void AtLine67AndColumn12()
        {
            Assert.IsTrue(AdminShellUtil.ComplyIdShort(""));
        }
    }
}

// This file was automatically generated by doctest-csharp.
// !!! DO NOT EDIT OR APPEND !!!
